apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: atul7cloudyuga/argocd-demo
  newTag: 9924da7d8289e64e64c61e830a03bd04505b5272
