apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: atul7cloudyuga/argocd-demo
  newTag: 7e6a2e940d1f70d9a09adffe9cf1147ce506723b
